# Generated by Django 4.1.3 on 2022-11-17 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_customuser_address_customuser_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='price_list',
            field=models.CharField(choices=[('1', 'Lista 1'), ('2', 'Lista 2')], default='1', max_length=2),
        ),
    ]
